primary: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/db_outplatform?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 10 #初始化连接
    max-idle: 20 #最大空闲连接
    min-idle: 5 #最小空闲连接
    max-active: 50 #最大连接数量
    log-abandoned: true #是否在自动回收超时连接的时候打印连接的超时错误
    remove-abandoned: true #是否自动回收超时连接
    remove-abandoned-timeout: 1800 #超时时间(以秒数为单位)
    max-wait: 30000
    min-evictable-idle-time-millis: 600000 #每隔五分钟检测空闲超过10分钟的连接
    time-between-eviction-runs-millis: 300000
    removeAbandoned: true
    removeAbandonedTimeout: 1800  
