server:
  port: 9526
  
hystrix.command.fallbackCmdA.execution.isolation.thread.timeoutInMilliseconds: 6000

spring:
  application:
    name: microservicecloud-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
  cloud: 
    gateway: 
      discovery: 
        locator: 
          enabled: true #开启从注册中心动态创建路由功能，利用微服务进行路由
      routes: 
        - id: microservicecloud-provider-dept-8001 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001
          uri: lb://MICROSERVICECLOUD-DEPT 
          predicates: 
            - Path=/dept/get/**
            - Method=get
          filters: 
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #redis-rate-limiter.replenishRate：允许用户每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 20 #redis-rate-limiter.burstCapacity：令牌桶的容量，允许在一秒钟内完成的最大请求数
                key-resolver: "#{@pathKeyResolver}" #key-resolver：使用SpEL按名称引用bean

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-gateway9526
    prefer-ip-address: true     #访问路径可以显示IP地址     
          