spring: 
  datasource: 
    url: jdbc:mysql://192.168.3.85:3306/db_outplatform?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 DruidDataSource作为数据源 