spring:
  profiles:
    active: dev
    
    
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  typeAliasesPackage: com.rongli.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true

