server:
  port: 8001
  
  
spring:
  application:
    name: outplatform-provider-api
  datasource:
    url: jdbc:mysql://localhost:3306/db_outplatform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 DruidDataSource作为数据源
  druid:
    initialSize: 5 #初始化连接大小
    minIdle: 5     #最小连接池数量
    maxActive: 20  #最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 from DUAL  #测试连接
    testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false       #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
    filters: stat,wall,slf4j   #配置扩展插件，常用的插件有=>stat:监控统计  slf4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
  redis: 
    database: 1  # Redis几号库
    host: 127.0.0.1  # Redis服务器地址  
    port: 6379  # Redis服务器连接端口  
    password: redis # Redis服务器连接密码（默认为空）  
    timeout: 10000
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接  

org:
  driver-path: com.rongli.driver.gzzl.GZZlTradeDriver
  powerbok: 
    url: http://www.powerbok.com/RLWebService/service/dotrade?wsdl        
  gzzl: 
    url: http://test.zlgysoft.cn:9088/OneCardSolution.asmx/OneCardBusiness
        
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: outplatform-provider-api-8001
    prefer-ip-address: true     #访问路径可以显示IP地址     